# Site settings
title: Critter Review
logo: /assets/images/logo.png
author:
  name: Philip Wahl
  email: wahl.philip@outlook.com
description: "Taking a critical look at vulnerabilities and trends, and reviewing tools to help unearth them!"

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
