# Site settings
title: Critter Review
# logo: /assets/images/logo3.png - Not sure I want an image
author:
  name: Philip Wahl
  email: wahl.philip@outlook.com
description: "Taking a critical look at vulnerabilities, trends, and reviewing tools to help unearth them!"

# Navigation Menu
nav:
  - title: "Home"
    url: "/"
  - title: "Vuln Trends"
    url: "/trends/"
  - title: "Tools"
    url: "/tools/"
  - title: "About"
    url: "/about/"

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
